name: Deployment Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-18
    steps:
      - name: Checkout to code
        uses: actions/checkout@v4
      - name: Listar main branch
        run: ls -l