name: Deployment Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to code
        uses: actions/checkout@v4
      - name: Listar main branch
        run: ls -l
      - name: Validar version de node
        run: node --version
      - name: Instalar node en servidor
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Validar version de node
        run: node --version
